CREATE DATABASE IF NOT EXISTS`market`;

USE `market`;

CREATE TABLE `TR_CLIENT`(
	`ID_CLIENT` INT NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(255) NOT NULL,
	`EMAIL` VARCHAR(255) NOT NULL,
	`PHONE` VARCHAR(255) NOT NULL,
	`PASSWORD` VARCHAR(255) NOT NULL,
    CONSTRAINT `pk_client` PRIMARY KEY (`ID_CLIENT`)
);

CREATE TABLE `TR_PRODUCT`(
	`ID_PRODUCT` INT NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(255) NOT NULL,
	`DESCRIPTION` VARCHAR(255) NOT NULL,
	`PRICE` INT NOT NULL,
	`IMG_URL` VARCHAR(255),
	CONSTRAINT `pk_product` PRIMARY KEY(`ID_PRODUCT`)
);

CREATE TABLE `TR_ORDER`(
	`ID_ORDER` INT NOT NULL AUTO_INCREMENT,
	`MOMENT` DATE NOT NULL,
	`ORDER_STATUS` INT NOT NULL,
    `CLIENT_ID` INT NOT NULL,
	CONSTRAINT `pk_order` PRIMARY KEY(`ID_ORDER`),
    CONSTRAINT `fk_tr_order_client_id` FOREIGN KEY (`CLIENT_ID`)
		REFERENCES `TR_CLIENT` (`ID_CLIENT`)
);

CREATE TABLE `TR_PAYMENT`(
	`ID_PAYMENT` INT NOT NULL AUTO_INCREMENT,
	`MOMENT` DATE NOT NULL,
	`ORDER_ID` INT NOT NULL,
	CONSTRAINT `pk_payment` PRIMARY KEY(`ID_PAYMENT`),
	CONSTRAINT `fk_tr_payment_order_id` FOREIGN KEY (`ORDER_ID`)
    		REFERENCES `TR_ORDER` (`ID_ORDER`)
);

CREATE TABLE `TR_ORDER_ITEM`(
    `QUANTITY` INT NOT NULL,
    `PRICE` DOUBLE NOT NULL,
    `PRODUCT_ID` INT NOT NULL,
    `ORDER_ID` INT NOT NULL,
	CONSTRAINT `fk_tr_order_item_product` FOREIGN KEY (`PRODUCT_ID`) 
		REFERENCES `TR_PRODUCT`(`ID_PRODUCT`),
	CONSTRAINT `fk_tr_order_item_order` FOREIGN KEY (`ORDER_ID`) 
		REFERENCES `TR_ORDER`(`ID_ORDER`),
	CONSTRAINT `pk_order_item` PRIMARY KEY (`PRODUCT_ID`, `ORDER_ID`)
);

CREATE TABLE `TR_CATEGORY`(
	`ID_CATEGORY` INT NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(255) NOT NULL,
	CONSTRAINT `pk_category` PRIMARY KEY(`ID_CATEGORY`)
);

CREATE TABLE `TR_PRODUCT_CATEGORY`(
	`PRODUCT_ID` INT NOT NULL,
    `CATEGORY_ID` INT NOT NULL,
    CONSTRAINT `fk_tr_product_category_product` FOREIGN KEY (`PRODUCT_ID`) 
		REFERENCES `TR_PRODUCT`(`ID_PRODUCT`),
	CONSTRAINT `fk_tr_product_category_category` FOREIGN KEY (`CATEGORY_ID`) 
		REFERENCES `TR_CATEGORY`(`ID_CATEGORY`),
	CONSTRAINT `pk_product_category` PRIMARY KEY (`PRODUCT_ID`, `CATEGORY_ID`)
);
